### ISSUE TITLE
为何要做权重替换

### ISSUE THREAD

**Issue by xilinniao123** [Legend94rz/jd2022-semi#1]
感谢分享！请问为什么“用uclanlp/visualbert-vqa-coco-pre初始化一个VisualBert，然后用youzanai/bert-product-title-chinese替换权重” 要做权重替换？

**Comment by Legend94rz** [comment]
我觉得有这几个原因吧，一是因为bert的权重训练得相当好了，不希望这部分再做大改动。二是训练数据的文本其实相对有限，虽然可以样本增广，但只是看似数量很多了，翻来覆去文本内容就那些，多样性不够。另外我好像做过从头train bert，发现根本不收敛。这种做法其实跟fine funing差不多了
